name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
            docker build -t ${{ secrets.USERNAME }}/lab2-app:1.0
            docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
            docker push ${{ secrets.USERNAME }}/lab2-app:1.0
